


export const GET_CAROUSEL = 'GET_CAROUSEL'
export const GET_FILMS = 'GET_FILMS'
export const SET_FILM_DANG_CHIEU = 'SET_FILM_DANG_CHIEU'
export const SET_FILM_SAP_CHIEU = 'SET_FILM_SAP_CHIEU'
export const SET_CINEMA = 'SET_CINEMA'
export const SET_DETAIL_FILM = 'SET_DETAIL_FILM'
export const SET_DATA_LOGIN = 'SET_DATA_LOGIN'


export const SET_LIST_TICKET_ROOM = 'SET_LIST_TICKET_ROOM'