
export const DISPLAY_LOADING = 'DISPLAY_LOADING'
export const HIDE_LOADING = 'HIDE_LOADING'

export const GET_CAROUSEL = 'GET_CAROUSEL'
export const SET_FILMS = 'SET_FILMS'

export const SET_FILM_NEW_IN = 'SET_FILM_NEW_IN'
export const SET_FILM_COMING_SOON = 'SET_FILM_COMING_SOON'

export const SET_CINEMA = 'SET_CINEMA'
export const SET_DETAIL_FILM = 'SET_DETAIL_FILM'
export const SET_INFO_FILM = 'SET_INFO_FILM'
export const SET_DATA_LOGIN = 'SET_DATA_LOGIN'


// User
export const SET_DATA_USER = 'SET_DATA_USER'
export const SET_LIST_USER = 'SET_LIST_USER'
export const SET_INFO_USER = 'SET_INFO_USER'
export const SET_ALL_TYPE_USER = 'SET_ALL_TYPE_USER'
export const SET_LIST_TICKET_ROOM = 'SET_LIST_TICKET_ROOM'
export const SET_LIST_CHAIR_OTHER_USER_BOOKING = 'SET_LIST_CHAIR_OTHER_USER_BOOKING'

export const BOOKING_CHAIR = 'BOOKING_CHAIR'
export const BOOKING_SUCCESS = 'BOOKING_SUCCESS'

export const SWITCH_TAB = 'SWITCH_TAB'
export const AUTO_SWITCH_TAB = 'AUTO_SWITCH_TAB'


